### ISSUE TITLE
Gestures inside of _buildContent are not recognized on first interaction

### ISSUE THREAD

**Issue by kamami** [ricnaaru/scrollable_bottom_sheet#10]
When tapping a button inside the _buildContent, the gesture is not fired! You need to tap it again, to see the expected result.

**Comment by ricnaaru** [comment]
are you using the latest version? because this should be fixed already..

**Comment by tp** [comment]
@ricnaaru Would you mind explaining what the root cause was / and how you fixed it? I was seeing the same in an adapted version of the draggable scrollable sheet from Flutter and probably ran into the same issue.

**Comment by ricnaaru** [comment]
#7 i suspected this what's happening, but if the bug is still occurs if you're using the latest version, please provide the steps to reproduce.. thanks

**Comment by ricnaaru** [comment]
i'm sorry that i forgot to roll the pull request to pub dev, 0.2.2 should fix the bug.. thanks for your report
