### ISSUE TITLE
v0.2.1 scrollable_bottom_sheet-Swift.h file not found

### ISSUE THREAD

**Issue by lavieAll** [ricnaaru/scrollable_bottom_sheet#11]
/Users/panliu/flutter/.pub-cache/hosted/pub.flutter-io.cn/scrollable_bottom_sheet-0.2.1/ios/Classes/ScrollableBottomSheetPlugin.m:2:9: fatal error: 'scrollable_bottom_sheet/scrollable_bottom_sheet-Swift.h' file not found
    #import <scrollable_bottom_sheet/scrollable_bottom_sheet-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by ricnaaru** [comment]
if in your "ios/Podfile" file you comment out `use_frameworks!`, you have to change
`#import <scrollable_bottom_sheet/scrollable_bottom_sheet-Swift.h>`
to
`#import <scrollable_bottom_sheet-Swift.h>`
