### ISSUE TITLE
Scrolling down all the way does a Navigator.pop

### ISSUE THREAD

**Issue by kjeremy** [ricnaaru/scrollable_bottom_sheet#3]
Hitting this: https://github.com/ricnaaru/scrollable_bottom_sheet/blob/master/lib/scrollable_bottom_sheet.dart#L84

This closes my app.

**Comment by ricnaaru** [comment]
currently my default feature will pop if it reaches 0.0 height, but i will add this feature soon, will notify for update at this thread #2..
