### ISSUE TITLE
Multiple widgets used the same GlobalKey

### ISSUE THREAD

**Issue by mopilo** [ricnaaru/scrollable_bottom_sheet#4]
After implementing this package and everything working well, i tried navigating to another screen from a button in my bottom sheet. But each time i tried to navigate back i get the above error.

`
                    children.add(GestureDetector(
        onTap: () {
          Navigator.push(
              context, new MaterialPageRoute(builder: (__) => new Newly()));
        },
        child: ListTile(
            title: Text(order.name), subtitle: Text("Qty: ${order.qty} pcs")),
      ));
`

Stack Trace 

I/flutter ( 8786): The following assertion was thrown building ScrollableBottomSheetByContent(state:
I/flutter ( 8786): _ScrollableBottomSheetByContentState#f67c4):
I/flutter ( 8786): Multiple widgets used the same GlobalKey.
I/flutter ( 8786): The key [LabeledGlobalKey<ScrollableBottomSheetState>#7a093] was used by multiple widgets. The
I/flutter ( 8786): parents of those widgets were:
I/flutter ( 8786): - ScrollableBottomSheetByContent(state: _ScrollableBottomSheetByContentState#797b7)
I/flutter ( 8786): - ScrollableBottomSheetByContent(state: _ScrollableBottomSheetByContentState#f67c4)
I/flutter ( 8786): A GlobalKey can only be specified on one widget at a time in the widget tree.
I/flutter ( 8786):
I/flutter ( 8786): When the exception was thrown, this was the stack:
I/flutter ( 8786): #0      GlobalKey._debugReserveFor.<anonymous closure> (package:flutter/src/widgets/framework.dart:172:11)
I/flutter ( 8786): #1      GlobalKey._debugReserveFor (package:flutter/src/widgets/framework.dart:190:6)
I/flutter ( 8786): #2      Element.updateChild.<anonymous closure> (package:flutter/src/widgets/framework.dart:2724:13)
I/flutter ( 8786): #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2727:6)
I/flutter ( 8786): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8786): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8786): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8786): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8786): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8786): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)

**Comment by ricnaaru** [comment]
I'm sorry for the long delay, currently i'm trying to figure out this issue, will inform you if it's fixed.. thanks

**Comment by ricnaaru** [comment]
So i'm still unable to figure out the GlobalKey error, it might because of my structure (ScrollableBottomSheetByContent create and return ScrollableBottomSheet, and measure its header and content's height after build), but i've created another alternative to control the bottom sheet via controller, so there is no need to use GlobalKey anymore.. It maybe not the best approach to fix this, but it's working well now, and i'll still improve it if i got better approach.. Please kindly see the example folder for reference.. 

Please change your dependency to the latest version, and if there is any difficulty to use it or there is an error, please inform me.. thanks

**Comment by mopilo** [comment]
Okay, thank lemme check it. will let you know of any issues

**Comment by mopilo** [comment]
All good, works well
