### ISSUE TITLE
getting error with flutter 1.2

### ISSUE THREAD

**Issue by ssg1110** [ricnaaru/scrollable_bottom_sheet#5]
Getting below error with flutter 1.2 and 
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                              1.2s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `scrollable_bottom_sheet` from
    `.symlinks/plugins/scrollable_bottom_sheet/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A scrollable_bottom_sheet

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing scrollable_bottom_sheet (0.1.0+2)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `scrollable_bottom_sheet` does not specify a Swift version and none of the targets
    (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author
    or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/
    target_validator.rb:115:in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/
    target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:459
    :in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:138
    :in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.
    rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in
    `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in
    `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an
    unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of
    a merge and  the unknown UUID is being discarded.

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no
    platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone X.

**Comment by ricnaaru** [comment]
currently im still running in flutter 1.0.0, so it's gonna take a while though, im sorry..

but i wanted to ask you, have you upgrade to androidX?
